use_frameworks!

platform :ios, '10.0'

target 'NewRelicVideoCore_Example' do
  pod 'NewRelicVideoCore', :path => '../'

  target 'NewRelicVideoCore_Tests' do
    inherit! :search_paths

    
  end
end
